spring:
  datasource:
    primary:
      url: jdbc:postgresql://localhost:5436/postgres
      username: glygen
      password: ENC(9GDuOYrvoTbqTITr5cGwuVyUYCYFx/aZgPZy/i21PRw=)
      driver-class-name: org.postgresql.Driver
      separator: ^^^ END OF SCRIPT ^^^
    secondary:
      url: jdbc:postgresql://localhost:5436/glycomedb
      username: glygen
      password: ENC(9GDuOYrvoTbqTITr5cGwuVyUYCYFx/aZgPZy/i21PRw=)
      driver-class-name: org.postgresql.Driver
      separator: ^^^ END OF SCRIPT ^^^
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
ncbi:
  api-key: ENC(/IuwNTHNR7ZDXFolnV/bnTfhj9l0Awr2UN1wBeWdKPzaARshqNOUTA3F7giwo6tq)
elsevier:
  api-key: ENC(opugcA1Xj2wFlu8T1uHurFH+PcWY4XvqcSiTzjeCQ/ClSvO5FfEYm9oYgWptly1U)
  
tablemaker:
  api-url: https://glygen.ccrc.uga.edu/tablemaker/api/
  user-id: cfgdata
  password: ENC(K7VPLELDFUvhkAWh1QjpKxy4JJHduoIm)